// <auto-generated />
using System;
using AulaClara.Infraestructura.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AulaClara.Infraestructura.Persistencia.Migraciones
{
    [DbContext(typeof(ContextoAulaClara))]
    [Migration("20260614213646_AjustarClasesConAlumnoMateria")]
    partial class AjustarClasesConAlumnoMateria
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("AulaClara.Dominio.Entidades.Alumno", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Edad")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("FechaActualizacionUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCreacionUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResponsableContacto")
                        .HasMaxLength(180)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResponsableNombre")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Alumnos", (string)null);
                });

            modelBuilder.Entity("AulaClara.Dominio.Entidades.AlumnoMateria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Activa")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("AlumnoId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaActualizacionUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaAsignacionUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCreacionUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MateriaId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MateriaId");

                    b.HasIndex("AlumnoId", "MateriaId")
                        .IsUnique();

                    b.ToTable("AlumnoMaterias", (string)null);
                });

            modelBuilder.Entity("AulaClara.Dominio.Entidades.Clase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AlumnoMateriaId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContenidoTrabajado")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaActualizacionUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaClaseUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCreacionUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Objetivo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AlumnoMateriaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Clases", (string)null);
                });

            modelBuilder.Entity("AulaClara.Dominio.Entidades.EjercicioClase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ClaseId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Consigna")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaActualizacionUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCreacionUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nivel")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<int>("Orden")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RespuestaEsperada")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClaseId");

                    b.ToTable("EjerciciosClase", (string)null);
                });

            modelBuilder.Entity("AulaClara.Dominio.Entidades.Materia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Activa")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaActualizacionUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCreacionUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId", "Nombre")
                        .IsUnique();

                    b.ToTable("Materias", (string)null);
                });

            modelBuilder.Entity("AulaClara.Dominio.Entidades.MaterialClase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ClaseId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaActualizacionUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCreacionUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Orden")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClaseId");

                    b.ToTable("MaterialesClase", (string)null);
                });

            modelBuilder.Entity("AulaClara.Dominio.Entidades.SeguimientoClase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Avances")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ClaseId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Dificultades")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaActualizacionUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCreacionUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Participacion")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProximoPaso")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClaseId")
                        .IsUnique();

                    b.ToTable("SeguimientosClase", (string)null);
                });

            modelBuilder.Entity("AulaClara.Dominio.Entidades.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaActualizacionUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCreacionUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("HashContrasenia")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("AulaClara.Dominio.Entidades.Alumno", b =>
                {
                    b.HasOne("AulaClara.Dominio.Entidades.Usuario", "Usuario")
                        .WithMany("Alumnos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AulaClara.Dominio.Entidades.AlumnoMateria", b =>
                {
                    b.HasOne("AulaClara.Dominio.Entidades.Alumno", "Alumno")
                        .WithMany("AlumnoMaterias")
                        .HasForeignKey("AlumnoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AulaClara.Dominio.Entidades.Materia", "Materia")
                        .WithMany("AlumnoMaterias")
                        .HasForeignKey("MateriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Alumno");

                    b.Navigation("Materia");
                });

            modelBuilder.Entity("AulaClara.Dominio.Entidades.Clase", b =>
                {
                    b.HasOne("AulaClara.Dominio.Entidades.AlumnoMateria", "AlumnoMateria")
                        .WithMany("Clases")
                        .HasForeignKey("AlumnoMateriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AulaClara.Dominio.Entidades.Usuario", "Usuario")
                        .WithMany("Clases")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AlumnoMateria");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AulaClara.Dominio.Entidades.EjercicioClase", b =>
                {
                    b.HasOne("AulaClara.Dominio.Entidades.Clase", "Clase")
                        .WithMany("Ejercicios")
                        .HasForeignKey("ClaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clase");
                });

            modelBuilder.Entity("AulaClara.Dominio.Entidades.Materia", b =>
                {
                    b.HasOne("AulaClara.Dominio.Entidades.Usuario", "Usuario")
                        .WithMany("Materias")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AulaClara.Dominio.Entidades.MaterialClase", b =>
                {
                    b.HasOne("AulaClara.Dominio.Entidades.Clase", "Clase")
                        .WithMany("Materiales")
                        .HasForeignKey("ClaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clase");
                });

            modelBuilder.Entity("AulaClara.Dominio.Entidades.SeguimientoClase", b =>
                {
                    b.HasOne("AulaClara.Dominio.Entidades.Clase", "Clase")
                        .WithOne("Seguimiento")
                        .HasForeignKey("AulaClara.Dominio.Entidades.SeguimientoClase", "ClaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clase");
                });

            modelBuilder.Entity("AulaClara.Dominio.Entidades.Alumno", b =>
                {
                    b.Navigation("AlumnoMaterias");
                });

            modelBuilder.Entity("AulaClara.Dominio.Entidades.AlumnoMateria", b =>
                {
                    b.Navigation("Clases");
                });

            modelBuilder.Entity("AulaClara.Dominio.Entidades.Clase", b =>
                {
                    b.Navigation("Ejercicios");

                    b.Navigation("Materiales");

                    b.Navigation("Seguimiento");
                });

            modelBuilder.Entity("AulaClara.Dominio.Entidades.Materia", b =>
                {
                    b.Navigation("AlumnoMaterias");
                });

            modelBuilder.Entity("AulaClara.Dominio.Entidades.Usuario", b =>
                {
                    b.Navigation("Alumnos");

                    b.Navigation("Clases");

                    b.Navigation("Materias");
                });
#pragma warning restore 612, 618
        }
    }
}
